server:
  #当前服务端口号
  port: 8089
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://118.25.151.35:3306/club?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: lastcy
    password: _Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    destroy-method: close
    filters: stat
    maxActive: 5
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    removeAbandoned: true
    removeAbandonedTimeout: 600
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 100
    #热部署--静态资源立即生效
    thymeleaf:
      cache: false
      encoding: UTF-8
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html,.jsp
      check-template-location: true
    #热部署生效
    devtools:
      restart:
        enabled: true
    #静态文件
    resources:
      static-locations: classpath:/static

mybatis:
  #实体类所做包
  type-aliases-package: fans.club.member.management.member.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml
