server:
  #当前服务端口号
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://118.25.151.35:3306/club?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: lastcy
    password: _Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    destroy-method: close
    filters: stat
    maxActive: 5
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    removeAbandoned: true
    removeAbandonedTimeout: 600
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 100